var fs = require('fs');
var path = require('path');

var foundPlugins = [];
fs.readFile(process.argv[5], function(err, data) {
	var config = JSON.parse(data);
	config.plugins.forEach(function(pluginDir) {
		var configFilePath = path.resolve([process.cwd(), pluginDir].join(path.sep));
		foundPlugins = foundPlugins.concat(fs.readdirSync(configFilePath));
	});
	var code = [
		'//WARNING This file is Generated by websocket.build.js. Modifications will be lost.',
	    'goog.provide(\"aurora.websocket.constants\");',
            '/**\n * @const\n*/',
	    'aurora.websocket.constants.plugins = '+ JSON.stringify(foundPlugins) + ';'

	];

	fs.writeFile(__dirname + path.sep + 'websocket.gen.shared.js', code.join('\r\n'), function(err) {
		console.log('Generated '+ __dirname + path.sep + 'websocket.gen.shared.js');
	});
});
